### ISSUE TITLE
iOS app does not update shown data points on sync in Apple Health goals

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#72] opened 2020-06-30 08:57 UTC
Another [bug report from the forum](https://forum.beeminder.com/t/ios-app-does-not-update-shown-data-points-on-sync-in-apple-health-goals/6796), created here at github.

## Expectations

tapping "sync 7 days" apparently does not
one does see a checkmark though
data in Apple Health App synced to a goal should be visible in the goal
data visible in the goal via the website should be visible in the app as well.

## Reality

goal data as shown on the website matched what was seen in App Health for the metric. App was off.

**Comment by krugerk** [comment] 2020-09-06 20:58
I have also seen apps integrating with HealthKit offer a sync button and show the data when the last sync took place.

After tapping 'sync 7 days', how can the user know it worked? How quickly should the user expect the goal to be updated?

**Comment by krugerk** [comment] 2021-02-11 10:50
#33 also concerns 'sync 7 days' apparently not working, particularly for meditation.

**Comment by theospears** [comment] 2022-12-10 22:43
I think this was caused by the app not refreshing data after syncing. If that is the case, this is fixed in HEAD.

**Closed by theospears** 2022-12-10 22:43 UTC
Labels: BUG, HealthKit
