### ISSUE TITLE
Baremin can be misleading/ambiguous

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#422] opened 2023-12-12 00:27 UTC
```[tasklist]
### Desiderata
- [ ] Replicata
- [ ] Determine if this is even in BeemiOS's ambit
- [ ] TBD
```

A user observes: 

> My readmore goal says "+58 due Sat night, 12:00am" on the website, but on iOS it says "+58 by Sun at 00:00"

## Cognata

* #228 
* #31 
* #26 
* #17 

_**Verbata**: beeminder day vs calendar day, midnight/noon confusion, safesum string,_

**Comment by theospears** [comment] 2024-01-29 06:15
I'm confused by this report.
1. I can't find any code in the app that would generate that string
2. I can only find examples of the app saying "+1 x due by 3am" or "Safe for xxx days" (which I believe is a string generated by the server via `safesum`).

Are there times `safesum` can generate the format the user reports? Is there a different field the app should use instead?

**Comment by theospears** [comment] 2024-09-15 01:25
Closing as cannot reproduce.

**Closed** 2024-09-15 01:25 UTC
Labels: BUG, ADO, cnr, UVI

**Comment by krugerk** [comment] 2024-09-17 06:51
The iOS app shows a goal's `safesum` as provided by the API.
 
🤔 `goal.safesum` does not appear to be documented at https://api.beeminder.com/#attributes-2.

I am not sure what the website shows; the classes around that element are `baremin` and `doom`.

It would seem that either the website is constructing its own string or the two (website and iOS app) are merely not using the same attribute.

**Comment by krugerk** [comment] 2024-09-17 06:55
> Closing as cannot reproduce.

It was reproducible for me:

Have a goal in the red. View it in the gallery in the ios app and view the same in the gallery on the website.

iOS app:
![image](https://github.com/user-attachments/assets/4e144a1b-add6-419c-945c-bfda80bc08f1)

website:
![image](https://github.com/user-attachments/assets/dff2f986-d6fe-4098-9b11-d24725919073)
website:
![image](https://github.com/user-attachments/assets/bd5108bc-88ef-418d-9005-4e95c6e9b1fd)
