### ISSUE TITLE
Totally blank screen when launching the app

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#37] opened 2020-05-05 19:24 UTC
User today: 

> I’ve seen this bug several times today on version 5.6.2: The scroll view is completely black when launching the app, it takes force closing and opening again to get it back. I’ve attached a video demonstration.

Screenshot from the video:

![image](https://user-images.githubusercontent.com/9928/81107047-66a7ce00-8ecb-11ea-8220-35f629dfb4a7.png)

**Comment by andrewpbrett** [comment] 2020-05-06 16:25
This was related to version checking; Apple sends back a string for a version like "5.6.2". When the app tried to compare this to a decimal version, it would sometimes (but somehow, not always, since I couldn't reproduce this in the simulator) incorrectly think the version was out of date.

This fix is in 5.6.3 which is on the way to the App Store review queue now.

**Comment by dreeves** [comment] 2020-05-07 23:28
User replied today: "Just a bug follow up, still getting the black screen error in the new update 5.6.3 (video attached)"

(Video seems legit from what I can tell! :))

**Comment by andrewpbrett** [comment] 2020-05-08 14:37
Yep, I can reproduce it now as well.

**Comment by 6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE** [comment] 2020-06-13 21:04
I had seen the same issue before as well. Now with 5.6.4 the goals are listed even after the app has been brought into the foreground after some time (no longer requiring the workaround force-close followed by app launch)

**Closed** 2020-08-07 16:03 UTC
Labels: BUG, zap
