### ISSUE TITLE
Documentation Defect: License is not displaying properly in README.md

### ISSUE THREAD

**Issue by emeraldfleur** [beeminder/BeeSwift#565] opened 2024-12-25 16:11 UTC
Hello,

# Environment

Safari 18, macOS Sequoia

# Replicata

Navigate to https://github.com/beeminder/BeeSwift.

# Expectata

<img width="475" alt="image" src="https://github.com/user-attachments/assets/4c542ecd-3e9a-477c-9736-349d459eeb2a" />

The above image.

# Actualata

License is not rendering properly in browser on beeminder/BeeSwift/README.md, as seen in the below screenshot. It also does not correctly link to the license, and merely redirects to the homepage of the repo.

<img width="964" alt="image" src="https://github.com/user-attachments/assets/f0cccd64-bca2-49f0-b8e1-1e8f11583150" />

**Comment by emeraldfleur** [comment] 2024-12-25 16:17
Fix proposed in PR #566.

**Comment by krugerk** [comment] 2024-12-25 17:24
This is a duplicate of #205. May it have more success this time 🤞.

**Comment by theospears** [comment] 2024-12-27 04:03
Fixed by #566

**Closed by theospears** 2024-12-27 04:03 UTC
Labels: BUG
