### ISSUE TITLE
Bug: beemiOS uses calendar days, not Beeminder days

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#35] opened 2020-04-13 07:48 UTC
From Garrison Taylor:

> iOS bug that has been bothering me: if your goals are due at (say) 5am, on the Website it has the date automatically count as the previous day until that 5am deadline, while on the app, it counts as the current calendar day.

**Comment by andrewpbrett** [comment] 2020-04-16 16:44
dupe of #29, which is closed and will go out in the next release

**Closed by andrewpbrett** 2020-04-16 16:44 UTC
Labels: bug
