### ISSUE TITLE
Standardized sort order

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#272] opened 2021-03-14 12:46 UTC
The sort preference in the settings menu could be removed. As it, it only affects the gallery anyway and not any of the other places listing goals within the app.

As a replacement, implement [standard sorting](https://forum.beeminder.com/t/my-beeminder-browser-extension/6648/23):

> intended sort order is like so:
>
> - Time remaining till derailing (or goal end date, whichever comes first)
> - Pledge
> - Goalname alphabetically

**Comment by andrewpbrett** [comment] 2021-03-14 16:04
This was a commonly requested feature to be able to sort the gallery in different ways, I don't think we should remove it. The standard sorting is referring to breaking ties and differences only show up if you have quite a few goals so it's fairly low on the priority list.

**Comment by dreeves** [comment] 2021-03-15 23:16
I think I agree with krugerk on this one, though maybe we can't put genie back in the bottle and take a way a feature that people are attached to. But it's pretty dangerous to ever let the goal list be out of standard urgency order if the user might not realize it. (I'm not sure how easy it is to not realize it or if it reverts to standard urgency order whenever you open the app, in which case it's probably safe enough.)

In general this is the kind of thing where I'd point to [the anti-settings principle](https://blog.beeminder.com/choices).

Aside from the settings/customization question, there should probably be a gissue for using the standardized sort order as the initial/default ordering.

**Comment by dreeves** [comment] 2021-03-29 21:40
Duplicate of #49

**Closed by dreeves** 2021-03-29 21:40 UTC
